version: "3.9"

networks:
  monitoring:
    driver: bridge

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:80"
      - "8082:82"
      - "8084:84"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "bridge"
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:
    external: true